"""
llm_routes.py — HTTP endpoints to test the LLM (Step 1).

ROLE OF THIS FILE:
  - Receives HTTP requests from the outside world (Postman, browser, curl)
  - Validates the request body using Pydantic (done automatically by FastAPI)
  - Calls llm_client to do the actual work
  - Returns the result as JSON

THIS FILE DOES NOT:
  - Know anything about how Ollama works (that's llm_client's job)
  - Know anything about tools, RAG, or the agent (later steps)
  - Parse JSON manually (FastAPI + Pydantic do that)

ENDPOINTS:
  GET  /api/llm/health    → ping Ollama, confirm it's alive
  POST /api/llm/chat      → send a message, get full response
  POST /api/llm/stream    → send a message, get streaming response
"""

from fastapi import APIRouter
from fastapi.responses import StreamingResponse

# Import the singleton LLM client (same object used everywhere)
from app.llm.llm_client import llm_client

# Import config to show model name in responses
from app.core.config import settings

# Import Pydantic models (shapes of request/response)
from app.schemas.models import LLMTestRequest, LLMTestResponse


# APIRouter is a "mini FastAPI" — groups related routes together
# prefix="/llm" means ALL routes in this file start with /llm
# tags=["..."] is just for grouping in the /docs UI
router = APIRouter(prefix="/llm", tags=["Step 1 - LLM"])


# =============================================================================
# ENDPOINT 1: Health Check
# Full path: GET /api/llm/health
# =============================================================================
@router.get("/health", summary="Ping Ollama and confirm model is responding")
def llm_health():
    """
    Sends a tiny prompt to Ollama to confirm:
      - Ollama is running
      - llama3.2:3b is loaded
      - Connection is working

    No request body needed (GET request).
    Returns a status dict — FastAPI auto-converts to JSON.
    """
    try:
        response = llm_client.chat(
            system_prompt="You are a system health checker. Be very brief.",
            user_message="Reply with exactly this text: LLM is online. Nothing else.",
        )
        return {
            "status": "ok",
            "model": settings.OLLAMA_MODEL,
            "embed_model": settings.OLLAMA_EMBED_MODEL,
            "ollama_url": settings.OLLAMA_BASE_URL,
            "llm_response": response.strip(),
        }
    except Exception as e:
        # If Ollama isn't running, return an error dict instead of crashing
        return {"status": "error", "detail": str(e)}


# =============================================================================
# ENDPOINT 2: Single-turn Chat
# Full path: POST /api/llm/chat
# =============================================================================
@router.post(
    "/chat",
    response_model=LLMTestResponse,   # FastAPI validates our return value matches this
    summary="Send a message to the LLM and get a full response",
)
def llm_chat(request: LLMTestRequest):
    """
    HOW FASTAPI HANDLES THIS:
      1. User sends POST request with JSON body
      2. FastAPI reads the JSON, validates it against LLMTestRequest
      3. Passes it to this function as `request` (already a Python object)
      4. We call llm_client.chat() with the values
      5. We return LLMTestResponse — FastAPI converts it to JSON automatically

    Test with Postman or /docs:
        POST /api/llm/chat
        {
            "system_prompt": "You are an expert AI content writer.",
            "user_message": "Explain what RAG is in 3 bullet points."
        }
    """
    response = llm_client.chat(
        system_prompt=request.system_prompt,
        user_message=request.user_message,
    )

    # Return a Pydantic model — FastAPI serializes it to JSON
    return LLMTestResponse(
        model=settings.OLLAMA_MODEL,
        response=response,
    )


# =============================================================================
# ENDPOINT 3: Streaming Chat
# Full path: POST /api/llm/stream
# =============================================================================
@router.post("/stream", summary="Stream the LLM response chunk by chunk (SSE)")
def llm_stream(request: LLMTestRequest):
    """
    Instead of waiting for the full response, this streams chunks
    as they are generated by the LLM.

    HOW STREAMING WORKS:
      1. llm_client.stream() is a Python generator (uses `yield`)
      2. Each `yield chunk` sends one piece of text to the client
      3. StreamingResponse wraps it in Server-Sent Events (SSE) format
      4. Client receives: "data: Hello\n\ndata:  world\n\ndata: [DONE]\n\n"

    Good for: long post generation, summaries — user sees progress live.

    Test with curl:
        curl -X POST http://localhost:8000/api/llm/stream
             -H "Content-Type: application/json"
             -d '{"user_message": "Write a 200 word article about AI."}'
    """
    def token_generator():
        """Inner generator: yields SSE-formatted chunks from the LLM."""
        for chunk in llm_client.stream(
            system_prompt=request.system_prompt,
            user_message=request.user_message,
        ):
            # SSE format: every message must be "data: <content>\n\n"
            yield f"data: {chunk}\n\n"
        # Signal to the client that streaming is complete
        yield "data: [DONE]\n\n"

    return StreamingResponse(
        token_generator(),
        media_type="text/event-stream",   # tells browser this is SSE
    )
